-- R__seed_ingredients_required.sql
-- 퀴즈용 필수 재료 이름을 ingredient 테이블에 없으면 삽입 (idempotent)

-- 참고: ingredient(name) 에 UNIQUE 인덱스가 있으면 더 안전합니다.
-- CREATE UNIQUE INDEX IF NOT EXISTS ux_ingredient_name ON ingredient(name);

INSERT INTO ingredient (name)
SELECT v.name
FROM (SELECT '토마토' AS name
      UNION ALL
      SELECT '오이'
      UNION ALL
      SELECT '당근'
      UNION ALL
      SELECT '감자'
      UNION ALL
      SELECT '옥수수'
      UNION ALL
      SELECT '사과'
      UNION ALL
      SELECT '시금치'
      UNION ALL
      SELECT '브로콜리'
      UNION ALL
      SELECT '마늘'
      UNION ALL
      SELECT '양파'
      UNION ALL
      SELECT '생강'
      UNION ALL
      SELECT '버섯'
      UNION ALL
      SELECT '소고기'
      UNION ALL
      SELECT '연어'
      UNION ALL
      SELECT '고등어'
      UNION ALL
      SELECT '참치'
      UNION ALL
      SELECT '새우'
      UNION ALL
      SELECT '오징어'
      UNION ALL
      SELECT '문어'
      UNION ALL
      SELECT '굴'
      UNION ALL
      SELECT '조개'
      UNION ALL
      SELECT '멸치'
      UNION ALL
      SELECT '계란'
      UNION ALL
      SELECT '달걀'
      UNION ALL
      SELECT '우유'
      UNION ALL
      SELECT '요거트'
      UNION ALL
      SELECT '바나나'
      UNION ALL
      SELECT '블루베리'
      UNION ALL
      SELECT '아몬드'
      UNION ALL
      SELECT '꿀'
      UNION ALL
      SELECT '레몬'
      UNION ALL
      SELECT '오렌지'
      UNION ALL
      SELECT '포도'
      UNION ALL
      SELECT '배'
      UNION ALL
      SELECT '복숭아'
      UNION ALL
      SELECT '딸기'
      UNION ALL
      SELECT '키위'
      UNION ALL
      SELECT '파인애플'
      UNION ALL
      SELECT '망고'
      UNION ALL
      SELECT '아보카도'
      UNION ALL
      SELECT '올리브오일'
      UNION ALL
      SELECT '카놀라유'
      UNION ALL
      SELECT '해바라기유'
      UNION ALL
      SELECT '코코넛오일'
      UNION ALL
      SELECT '들깨'
      UNION ALL
      SELECT '들기름'
      UNION ALL
      SELECT '참기름'
      UNION ALL
      SELECT '버터'
      UNION ALL
      SELECT '두부'
      UNION ALL
      SELECT '현미'
      UNION ALL
      SELECT '귀리'
      UNION ALL
      SELECT '퀴노아'
      UNION ALL
      SELECT '고구마'
      UNION ALL
      SELECT '보리'
      UNION ALL
      SELECT '콩'
      UNION ALL
      SELECT '렌틸콩'
      UNION ALL
      SELECT '병아리콩'
      UNION ALL
      SELECT '율무'
      UNION ALL
      SELECT '브라질너트'
      UNION ALL
      SELECT '피스타치오'
      UNION ALL
      SELECT '호두'
      UNION ALL
      SELECT '캐슈넛'
      UNION ALL
      SELECT '참깨'
      UNION ALL
      SELECT '검은깨'
      UNION ALL
      SELECT '치아씨드'
      UNION ALL
      SELECT '아마씨'
      UNION ALL
      SELECT '카카오닙스'
      UNION ALL
      SELECT '된장'
      UNION ALL
      SELECT '고추장'
      UNION ALL
      SELECT '간장'
      UNION ALL
      SELECT '소금'
      UNION ALL
      SELECT '설탕'
      UNION ALL
      SELECT '후추'
      UNION ALL
      SELECT '고춧가루'
      UNION ALL
      SELECT '카레'
      UNION ALL
      SELECT '계피'
      UNION ALL
      SELECT '김치'
      UNION ALL
      SELECT '빵'
      UNION ALL
      SELECT '초콜릿'
      UNION ALL
      SELECT '커피'
      UNION ALL
      SELECT '녹차'
      UNION ALL
      SELECT '홍차'
      UNION ALL
      SELECT '물'
      UNION ALL
      SELECT '탄산음료'
      UNION ALL
      SELECT '에너지드링크'
      UNION ALL
      SELECT '주스'
      UNION ALL
      SELECT '식초'
      UNION ALL
      SELECT '두유'
      UNION ALL
      SELECT '치즈') AS v
         LEFT JOIN ingredient i ON i.name = v.name
WHERE i.id IS NULL;